### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by ariarijp** [toritori0318/redash-dynamic-query#9]
Hi, toritori0318.

Do you have a plan to publish this package on PyPI?

**Comment by toritori0318** [comment]
Hi, ariarijp.

> Do you have a plan to publish this package on PyPI?

OK, If need be, I will do it.
Could you please wait for one week or so?

**Comment by ariarijp** [comment]
Great!
I'm looking forward to that day.

Thanks

**Comment by toritori0318** [comment]
@ariarijp  shipped!
https://pypi.python.org/pypi/redash-dynamic-query/1.0.0
